Feature/4 statistics
snowsergo/iOS-FakeNFT-StarterProject-Public pull request #1
Opened 2023-05-28 22:51 UTC by snowsergo

2023-05-29 16:11 UTC, mahlenko reviewed
В целом, вроде норм :) Допилить индикаторы загрузки.

2023-05-29 16:11 UTC, mahlenko commented on FakeNFT/Resources/CollorAsset.swift
> +    case black, blue, white, grey, lightGrey, yellow
У меня такой вариант не прокатил на ревью, подсмотрел у тебя. Кейсы плохо писать в 1 строку, лучше делить на отдельные.

2023-05-29 16:11 UTC, mahlenko commented on FakeNFT/Resources/ImageAsset.swift
> +enum ImageAsset: String, CaseIterable {
Не используемое лучше убирать из кода, комменты ниже выделенного)

2023-05-29 16:11 UTC, mahlenko commented on FakeNFT/Scenes /StatisticsPage/StatisticsPageViewController.swift
> +        view.backgroundColor = .white
Наверное лучше .asset использовать

2023-05-29 16:11 UTC, mahlenko commented on FakeNFT/Scenes /StatisticsPage/StatisticsPageViewController.swift
> +        menuButton.tintColor = .black
```suggestion
menuButton.tintColor = .asset(.black)
```

Тут тоже наверное из .asset - экстеншн у тебя есть, но не используются. Может еще где-то по коду использование цвета без .asset есть.

2023-05-29 16:11 UTC, mahlenko commented on FakeNFT/Scenes /StatisticsPage/StatisticsPageViewController.swift
> +            tableView.bottomAnchor.constraint(equalTo: view.bottomAnchor, constant: -100)
Констрейты наверное не к view, а к `view.safeAreaLayoutGuide `так тебе **не нужно будет** задавать нижний отступ в -100. SafeArea будет учитывать navbar. (но мне пока сложно по коду ориентироваться, нужно запускать проект)

2023-05-29 16:11 UTC, mahlenko commented on FakeNFT/Scenes /StatisticsPage/StatisticsPageViewController.swift
> +            count: String(user.nfts.count),
string для количества (числа)?
```suggestion
```

Как вариант, может быть всю модель передавать, вместо отдельных пропсов. Хотя так точнее и наверное, понятнее. Но если в ячейке что-то изменится, придется в нескольких местах делать изменения.

2023-05-29 16:11 UTC, mahlenko commented on FakeNFT/Scenes /StatisticsPage/StatisticsPageViewModel.swift
> +enum SortType: String {
Похоже все пункты будут начинаться с **by**. Может есть смысл избавиться от приставки. Ну и String в значении, не знаю зачем. Кажется избыточным.

2023-05-29 16:11 UTC, mahlenko commented on FakeNFT/Scenes /StatisticsPage/UserViewCell.swift
> +        view.backgroundColor = .red
.asset

2023-05-29 16:11 UTC, mahlenko commented on FakeNFT/Scenes /StatisticsUserPage/StatisticsUserPageViewController.swift
> +        view.backgroundColor = .white
😊

2023-05-29 16:11 UTC, mahlenko commented on FakeNFT/Scenes /StatisticsUserPage/StatisticsUserPageViewController.swift
> +        view.widthAnchor.constraint(equalToConstant: imageSize.width).isActive = true
NSLayoutConstraint.activate?

Я у себя указывал ширину, а высоту в соотношении 1х1 ширины. Все на констрейтах, без `CGSize(width: 70, height: 70)`

2023-05-29 16:11 UTC, mahlenko commented on FakeNFT/Scenes /StatisticsUserPage/StatisticsUserPageViewController.swift
> +        button.titleLabel?.font = UIFont.systemFont(ofSize: 16)
ок, но может использовать .asset под шрифты?

2023-05-29 16:11 UTC, mahlenko commented on FakeNFT/Scenes /StatisticsUserPage/StatisticsUserPageViewController.swift
> +        button.layer.borderColor = UIColor.black.cgColor
.asset?

2023-05-29 16:11 UTC, mahlenko commented on FakeNFT/Scenes /StatisticsUserPage/StatisticsUserPageViewController.swift
> +    private func openWebView() {
Кажется нет progressBar?

2023-05-29 16:11 UTC, mahlenko commented on FakeNFT/Scenes /StatisticsUserPage/StatisticsUserPageViewModel.swift
> +        let request = Request(endpoint: URL(string: defaultBaseUrl + "/users" + "/\(userId)"), httpMethod: .get)
Не хватает индикатора загрузки, того же ProgressHUD

2023-05-30 13:07 UTC, mahlenko commented on FakeNFT/Resources/CollorAsset.swift
>  enum ColorAsset: String, CaseIterable {
CaseIterable - не думаю что нужен, он позволит тебе работать с Енам как с массивом вроде. А ты вряд ли его будешь использовать так.

2023-05-30 19:36 UTC, IBDesignable commented
@snowsergo привет! я не нашла файла с декомпозицией работ и описания дипломной работы (архитектура, верстка, оценка времени)

пожалуйста, добавь их в шапку ПР и верни работу на проверку ❤️

2023-05-31 20:20 UTC, IBDesignable requested changes

2023-05-31 20:20 UTC, IBDesignable commented on feature-4.md
> +- ✅ Изучение дефолтного сетевого клиента **[1 час]**
Очень хорошо что была заложена работа на ресеч

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Resources/Config.swift
> +let defaultBaseUrl = "https://64611c69491f9402f49ecce1.mockapi.io/api/v1"
Хорошо что есть константа. Можно лучше: прятать глобальный контекст в структуру или неймспейс с enum Constants. Как это делали в предыдущих проектах

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserCollectionPage/StatisticsNftCell.swift
> +            bucketButton.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: -11),
Все кнопки с маленькими иконками без тела (без бекграунда), по рекомендациям [Apple HIG](https://developer.apple.com/design/human-interface-guidelines/buttons#Best-practices) должны быть минимум 44на44. Большая область поддержки помогает пользователям попадать по кнопкам. Поэтому верстать от иконки без охранных областей – не apple-way. 

Наш дизайнер этого тоже не учел, выбрав размер 40на40, но это уже лучше чем исходный размер иконки. Нужно будет поправить, согласно макетам (в идеале на работе: написать дизайнеру, мол не надо так)
<img width="165" alt="Снимок экрана 2023-05-31 в 22 12 19" src="https://github.com/snowsergo/iOS-FakeNFT-StarterProject-Public/assets/121577115/f81c6bef-d4fd-4543-936f-19cfec4a1811">

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserCollectionPage/StatisticsNftCell.swift
> +            priceLabel.leadingAnchor.constraint(equalTo: contentView.leadingAnchor, constant: 0)
Не хватает нижнего констрейнта, элементы вылезлы за пределы ячейки:
<img width="220" alt="Снимок экрана 2023-05-31 в 22 18 17" src="https://github.com/snowsergo/iOS-FakeNFT-StarterProject-Public/assets/121577115/9c2bcf81-9917-4757-9681-ba5e35450e5b">

Ячейка в дизайне выглядит так:
<img width="250" alt="Снимок экрана 2023-05-31 в 22 19 08" src="https://github.com/snowsergo/iOS-FakeNFT-StarterProject-Public/assets/121577115/d01bc752-5088-4bfd-b73a-72f8acafe39a">

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserCollectionPage/StatisticsNftCell.swift
> +            likeButton.trailingAnchor.constraint(equalTo: imageBackground.trailingAnchor, constant: -8),
Здесь такая же проблема
<img width="205" alt="Снимок экрана 2023-05-31 в 22 19 43" src="https://github.com/snowsergo/iOS-FakeNFT-StarterProject-Public/assets/121577115/8ea4e8df-482d-46c1-af63-e8eadcbf009c">

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserCollectionPage/StatisticsNftCell.swift
> +        label.font = .caption2
здесь ожидается medium 10
по факту 13шка:
<img width="613" alt="Снимок экрана 2023-05-31 в 22 23 20" src="https://github.com/snowsergo/iOS-FakeNFT-StarterProject-Public/assets/121577115/18d19d0e-8297-45a3-886d-515b6fb45f5c">

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserCollectionPage/StatisticsNftCell.swift
> +        configure(with: nil)
не вызван метод super – проверь что у всех override методов в проекте вызван супер.

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserCollectionPage/StatisticsNftCell.swift
> +    let ratingView = RatingView()
точно нужно оставить публичный доступ?

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserCollectionPage/StatisticsNftCell.swift
> +        guard let url = nft?.images[0], let validUrl = URL(string: url) else {return}
очень много логики в простой вьюхе: в идеале здесь должна приходить готовая презентационная модель, от ячейки требуется только в свойства переместить значения.

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserCollectionPage/StatisticsNftCell.swift
> +    override func prepareForReuse() {
Ожидается что сначала перечисляются свойства, затем методы. иниты, овверайды, паблик/прайваты, и ibaction/objc методы. 

Как минимум свойства с методами стоит поменять местами

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserCollectionPage/StatisticsUserCollectionPageViewController.swift
> +        return CGSize(width: (collectionView.bounds.width - 16 - 16 - 16) / 3, height: 180)
здесь можно упростить:
`collectionView.bounds.width / 3 - 16`

 а вообще 3 и 16 - достаточно магические числа, чтобы спросить а что это такое?
В таких случаях рекомендуется иметь список констант, или хотя бы перед использованием обозначить что это за число. 3- numberOfColums, 16 - offset(не знаю что за отступ, но хорошо бы конкретный отступ обозначить)

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserCollectionPage/StatisticsUserCollectionPageViewController.swift
> +        let safeArea = view.safeAreaLayoutGuide
очень круто что вынес в отдельную переменную – сэкономил длину строки)

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserCollectionPage/StatisticsUserCollectionPageViewController.swift
> +    private var nfts: [Int]?
если ты используешь MVVM то nft - часть модели, и должна быть изолирована от слоя вью. Это архитектурная ошибка, надо разобраться до сдачи  готовой работы

В идеале MVVM модуль должен собираться, например фабрикой, и элементы MVVM модуля сами не создают свои зависимости. 

Модель: данные + сервисы, все создается/получается из вне и используется для создания ViewModel (через инит инджектируем). 
Контроллер создается с одной единственной зависимостью ViewModel. 

Вместо фабрики можно создавать перед тем как навигировать на экранный модуль, просто делать это внутри функции другого экрана. 
Если делать с фабрикой то она может принимать какие-то данные для конфигурирования (nfts), на выходе давать контроллер:
```swift
final class StatisticsUserCollectionPageAssebmly {
  func assemble(nfts: [Int]) -> UIViewController {
    let viewModel = ViewModel(nfts, DefaultNetworkClient())
    let viewController = StatisticsUserCollectionPageViewController(viewModel: viewModel) 
    // здесь если модуль реализован на перекрестных слабых ссылках-кложурах, настраиваются байдинговые связи
    viewModel.onChange = viewController.change
    return viewController 
  }
}
```

вызывать перед пушем: 
```swift
let vc = StatisticsUserCollectionPageAssebmly().assemble(...)
present(vc)
```

цель всего этого – избавиться от двух вещей: 
- убрать знание о модели из вью (изолировать), 
- убрать ответственность с вью по созданию ViewModel и настройки своего модуля.

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserCollectionPage/StatisticsUserCollectionPageViewController.swift
> +    private var nfts: [Int]?
Полагаю комментарий будет относится ко всем MVVM модулям

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserCollectionPage/Components/RatingView.swift
> +class RatingView: UIStackView {
Если не требуется наследованное, то стоит закрыть final – это будет консистентно по отношению к остальным классам в проекте

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserCollectionPage/StatisticsUserCollectionPageViewModel.swift
> +    let defaultNetworkClient = DefaultNetworkClient()
нужно добавить модели собственный инит. негоже свои зависимости создавать :)

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserCollectionPage/StatisticsUserCollectionPageViewModel.swift
> +    private(set) var nfts: [Nft]=[] {
```suggestion
    private(set) var nfts: [Nft] = [] {
```

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserCollectionPage/StatisticsUserCollectionPageViewModel.swift
> +        }
вся работа этого метода – задаче не ViewModel, а слоя Model(сервиса). Ожидается что у тебя будет сервис, который умеет делать такие запросы, и возвращать результат. 

Если останется время – круто было бы разделить.

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserCollectionPage/StatisticsUserCollectionPageViewModel.swift
> +        showLoader(true)
правильно понимаю, что в API не хватило ручки на запрос данных одним запросом?

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserCollectionPage/StatisticsUserCollectionPageViewModel.swift
> +                        print("___failure")
по-хорошему если оставишь так, то придется поставить минус по части обработки ошибок. 

Если здесь по задаче не надо никак обрабатывать для пользователя ошибку, то лучше переписать 

```swift
guard case .success(let nft) = result else { dispatchGroup.leave(); return }
DispatchQueue.main.async { self.nfts.append(nft); dispatchGroup.leave() }
```
только замыкания на деле раскрыть, я тут для краткости в одну строчку пишу)

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserPage/StatisticsUserPageViewController.swift
> +    private let labelView: UILabel = UILabel()
что за лейбл не понятно :) названия нужно давать понятные, чтобы никто случайно в трех соснах не потерялся)

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserPage/StatisticsUserPageViewController.swift
> +        self.userId = userId
userID - это тоже модель, ее надо спрятать во viewmodel

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserPage/StatisticsUserPageViewController.swift
> +    private lazy var collectionButtonLabel: UILabel = {
```suggestion
    }()
    
    private lazy var collectionButtonLabel: UILabel = {
```

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserPage/StatisticsUserPageViewController.swift
> +        stackView.isUserInteractionEnabled = true
не поняла, почему UITapGestureRecognizer понадобился, ты же с кнопкой работаешь. Почему на нее экшен не повесить?

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserPage/StatisticsUserPageViewController.swift
> +        navigationController?.pushViewController(viewController, animated: true)
ожидается тут отдельный экран, как делали в imagefeed.

Еще обрати внимание, сейчас ты пушишь в навигационный стек. Это приводит к тому, что пользователю доступен таббар – в макетах же его нет на таком экране.

Делается так: презентится модалка. В модалку помещается другой UINavVC с рутом на вебвью контроллер. 
Тогда будет и навбар по дизайну, и таббара не будет.

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserPage/StatisticsUserPageViewController.swift
> +        view.addSubview(collectionButton)
Такие экраны лучше складывать на scrollView, на случай, если у тебя маленький экран, а какое-нибудь биопользователя состоит из лонгрида и вымещает все кнопки за границы экрана.  Так получается дополнительная гибкость, на случай если в продукте захотят наполнить экран: он уже будет скролящимся.

<img width="458" alt="Снимок экрана 2023-05-31 в 23 04 31" src="https://github.com/snowsergo/iOS-FakeNFT-StarterProject-Public/assets/121577115/7777bc20-b594-4493-bba0-acb533a31267">

Можно решить иначе: выяснить ограничение по длине на этот текстовый блок и заблокировать в лейбле.

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserPage/StatisticsUserPageViewModel.swift
> +                    print("___failure")
не обработана ошибка, по идее надо показывать экран с возможностью повторить 

https://www.figma.com/file/k1LcgXHGTHIeiCv4XuPbND/FakeNFT-(YP)?type=design&node-id=641%3A28990&t=fR1YtOn94dfgp05o-1

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserPage/StatisticsUserPageViewModel.swift
> +    func getUser(userId: String) {
```suggestion
    let defaultNetworkClient = DefaultNetworkClient()
    
    func getUser(userId: String) {
```

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsUserPage/StatisticsUserPageViewModel.swift
> +        let request = Request(endpoint: URL(string: defaultBaseUrl + "/users" + "/\(userId)"), httpMethod: .get)
аналогично предыдущему комментарию - работа в этом методе не часть слоя с вьюмоделью, нужно убрать запрос в сервис ( сетевой клиент кстати зависимость этого сервиса, а не модели)

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsPage/UserViewCell.swift
> +        insertSubview(backView, at: 0)
у ячеек таблиц и коллекций вьюшки надо складывать на contentMode – иначе могут быть неочевидные проблемы с отображением (пропасть/разъехаться за милое дело), отлаживать такие вещи обычно тяжело(

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsPage/UserViewCell.swift
> +        ])
элементы этой ячейки хорошо верстаются на стеках. Хорошо бы продемонстрировать работу со стеками – собирать экраны на стеках может быть очень полезным, на собеседованиях могут попросить на словах рассказать как сверстаешь какой-нибудь вложенный макет.

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsPage/UserViewCell.swift
> +            indexView.leadingAnchor.constraint(equalTo: leadingAnchor, constant: 16),
16 по бокам – это отсуп таблицы, а не ячеек. Внешние отступы обычно не прячут во внутренние вьюхи. 
![Uploading Снимок экрана 2023-05-31 в 23.15.49.png…]()

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsPage/UserViewCell.swift
> +    func configure(index: String? = nil, label: String? = nil, count: String? = nil, url: String? = nil) {
вместо перечисления всех аргументов, лучше передавать модель данных

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsPage/UserViewCell.swift
> +        configure()
super

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsPage/StatisticsPageViewModel.swift
> +enum SortType: String {
Согласна, на уровне приложения можно отказаться от by, и спроектировать имя функции так sorted(by type: SortType): при вызове будет красиво sorted(by: .name)

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsPage/StatisticsPageViewModel.swift
> +                    print("___failure")
Не обработана ошибка.

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsPage/StatisticsPageViewController.swift
> +        let viewController = StatisticsUserPageViewController(userId: user.id)
вот здесь можно было бы собрать viewModel от user.id и настроить связи - как описывала выше

2023-05-31 20:20 UTC, IBDesignable commented on FakeNFT/Scenes /StatisticsPage/StatisticsPageViewController.swift
> +        alert.addAction(UIAlertAction(title: "Закрыть", style: .cancel))
очень круто что действия переданы модели)

2023-06-04 20:07 UTC, snowsergo commented on FakeNFT/Resources/Config.swift
> +let defaultBaseUrl = "https://64611c69491f9402f49ecce1.mockapi.io/api/v1"
тут надо смотреть что у всей команды

2023-06-04 20:46 UTC, snowsergo commented on FakeNFT/Scenes /StatisticsPage/StatisticsPageViewModel.swift
> +                    print("___failure")
мне больше нравится называть и типы и функцию так чтобы каждый понимал что она делает, названия типов .name. и .count совсем не говорящие  byName и byCount как бы объясняют сами что это типы сортировки ПО имени и ПО количеству

2023-06-19 21:30 UTC, closed without merging